### ISSUE TITLE
About the preprocessed dataset

### ISSUE THREAD

**Issue by jyhong0304** [pietrobarbiero/entropy-lens#1]
Hello,

First of all, your paper inspired me greatly, and thank you so much for sharing your codes.
I'm trying to reproduce your experimental results based on your code repository, and I have some questions about the preprocessed dataset you used.
In `load_dataset.py`, it seems that the preprocessed dataset, for example, `cub200.csv` for CUB-200-2011, were used.
I may missed something but I could access only raw data from the links provided by your supplementary material. 
So, could you please share your preprocess dataset with me or let me know how to generate the dataset you used?
Thank you.

Regards,
Jinyung Hong

**Comment by pietrobarbiero** [comment]
Hi Jinyung!

We preprocessed CUB using the code from this repo: [https://github.com/pietrobarbiero/logic_explained_networks/blob/master/experiments/CUB_200_2011/concept_extractor_cub.py](https://github.com/pietrobarbiero/logic_explained_networks/blob/master/experiments/CUB_200_2011/concept_extractor_cub.py). 

Here's an example on how it was used: [https://github.com/pietrobarbiero/logic_explained_networks/blob/master/experiments/experiment_cub.ipynb](https://github.com/pietrobarbiero/logic_explained_networks/blob/master/experiments/experiment_cub.ipynb)
Let me know if you need more details :)

Best wishes,
Pietro

**Comment by jyhong0304** [comment]
Hi, Pietro.

Thank you so much for sharing the links and the dataset with me!
It worked perfectly!

Regards,
Jinyung Hong
